### PR TITLE
Missing dependency Scalar::Util

### PR DESCRIPTION
**Pull request by jonasbn**
We have an application using Parse::Method::Signatures - if exploded with the following error:

Error: Undefined subroutine &Parse::Method::Signatures::blessed called at  ... /perl5/lib/perl5/Parse/Method/Signatures.pm line 334.

The fix of adding Scalar::Util seems to do the job.

jonasbn

### CODE REVIEW

**Comment by kentfredric** [comment]
Can you provide a test I can run locally to confirm this bug? 

`Moose.pm` exports `blessed` and depends on `Scalar::Util`, so this bug shouldn't be happening. 

Can you report your Moose version and Scalar::Util version?

**Comment by kentfredric** [comment]
Also, both of these should work. 

```perl
perl -MMoose -E 'say blessed(bless {},__PACKAGE__)' 
main
```
```perl
perl -MMoose -E 'use namespace::clean -except => q[meta]; say blessed(bless {},__PACKAGE__)' 
main
```

**Comment by karenetheridge** [comment]
Please definitely provide the version of Moose under which this problem occurs, as `use Moose;` will export `blessed` for you.

**Comment by jonasbn** [comment]
Hi @kentfredric and @karenetheridge,

This issue occurred a long time ago, I am in not in a position position where I will be able to recreate the environment under which this error occurred. I never suspected Moose, so I never investigated. Perhaps comments in the code could have pinpointed this.

Please reject it.

jonasbn

**Comment by jonasbn** [comment]
Checking the [Changes file](https://metacpan.org/changes/distribution/Moose) for Moose, I would expect the use of Moose would be version 2.1206

**Comment by jonasbn** [comment]
Based on your feedback, this PR does not make sense since [Moose](https://metacpan.org/pod/Moose) should provide `blessed` and not [Scalar::Util](https://metacpan.org/pod/Scalar::Util).

**Comment by kentfredric** [comment]
To an extent I want to do this, because relying on Moose providing blessed seems like a fragile design choice. All issues, even historical "need a more recent Moose" are still interesting if we can reproduce them.

Just having a reliable way to reproduce the problem is key to solving it. ( Otherwise we wouldn't know we'd fixed it :) )

**Comment by karenetheridge** [comment]
While we don't plan on deprecating the exporting of `blessed` from Moose, because it would break lots of things everywhere, it's certainly reasonable to explicitly export blessed from Scalar::Util simply for clarity.

It always has been exporting blessed, so if it wasn't working, there was a bug to be fixed.  Please let us know (e.g. on irc or via Moose's bug reporter) if you see anything like this occurring!  cheers.

:)

**Comment by jonasbn** [comment]
If I run into problems again I will let you know. I am not a Moose user myself. so I never investigated that branch.

Thanks for responding, now get back to coding

**Pull request closed without merging**
