### PR TITLE
Fix unescaped { } ( RT#114385)

### PR DESCRIPTION
**Pull request by kentfredric**
{ in QR now needs escaping.

### CODE REVIEW

**Comment by ashb** [comment]
👍 I've take the MST approach - you now have colab here and on PAUSE :) Feel free to cut a release.

**Comment by kentfredric** [comment]
PAUSE perms suggest otherwise :/
```
module	userid	type	owner
Parse::Method::Signatures 	ASH 	first-come 	ASH
Parse::Method::Signatures 	FLORA 	co-maint 	ASH
Parse::Method::Signatures 	ILMARI 	co-maint 	ASH
Parse::Method::Signatures 	PDCAWLEY 	co-maint 	ASH
```

**Comment by kentfredric** [comment]
Test push also fails.

git push cpan future-1.003017
ERROR: Permission to ashb/Parse-Method-Signatures.git denied to kentfredric.

**Comment by kentfredric** [comment]
Oh. I guess I have to accept the invite first. Duh.

**Comment by ashb** [comment]
> Added KENTNL to co-maintainers of Parse::Method::Signatures.
>
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Bindable.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Named.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Placeholder.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Positional.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Unpacked.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Unpacked::Array.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Param::Unpacked::Hash.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::ParamCollection.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Sig.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::TypeConstraint.
> 
> Added KENTNL to co-maintainers of Parse::Method::Signatures::Types.

Try now?

**Comment by kentfredric** [comment]
:) 

Status: Successfully indexed
============================

     module : Parse::Method::Signatures
     version: 1.003017
...

**Pull request merged**
